### ISSUE TITLE
panel icons

### ISSUE THREAD

**Issue by r8b7xy** [z1lt0id/.Dotfiles#2]
Could you tell me where I can find panel icons from this [screenshot](http://i3.minus.com/ibbOA7nTrGwmOK.png) listed at [unixporn](http://www.reddit.com/r/unixporn/comments/2vc6eu/bspwm_my_second_month_with_bspwm_joooyyyy/)?

**Comment by z1lt0id** [comment]
Hi r8b7xy,

It is actually a font that has those panel icons built into it.  If you
look in the config file in the panel directory under bspwm you'll notice a
font called stlarch.  If you are using Arch it is in the AUR repos.
Otherwise you can find it here.

http://sourceforge.net/projects/stlarchfont/
